package com.cdac.gaaddimitra.services;

import java.util.List;

import com.cdac.gaaddimitra.entitiesDTO.TransactionDto;

public interface TransactionService {
	
	public List<TransactionDto> getAllTransactions();

	long totalTransactions();

	void addTransaction(TransactionDto transactionDto);

	TransactionDto getTransactionById(int id);

	/**
	 * Creates and saves an initial transaction record before sending it to Razorpay.
	 * This record acts as a log of the payment attempt.
	 * 
	 * @param tDto The transaction data from the frontend.
	 * @param razorpayOrderId The order_id generated by Razorpay.
	 * @param status The initial status from Razorpay (usually "created").
	 */
	void createInitialTransaction(TransactionDto tDto, String razorpayOrderId, String status);
}
